# https://taskfile.dev

version: '3'

tasks:
  dev:
    desc: Run Next.js development server
    cmds:
      - pnpm dev

  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  lint:
    desc: Run Biome linter
    cmds:
      - pnpm lint

  format:
    desc: Format code using Biome
    cmds:
      - pnpm format

  check:
    desc: Check Biome rules and apply safe fixes (incl. formatting)
    cmds:
      - pnpm check

  check:unsafe:
    desc: Check Biome rules and apply all fixes (incl. unsafe and formatting)
    cmds:
      - pnpm check:unsafe

  test:
    desc: Run unit/component tests (Vitest) in watch mode
    cmds:
      - pnpm test

  test:ui:
    desc: Run unit/component tests (Vitest) with interactive UI, available at http://localhost:51204/__vitest__/
    cmds:
      - pnpm test:ui

  test:run:
    desc: Run all unit/component tests (Vitest) once
    cmds:
      - pnpm test:run

  test:storybook:
    desc: Run Storybook story tests (Vitest browser mode via Playwright)
    cmds:
      - pnpm test:storybook

  test:all:
    desc: Run unit/component tests + Storybook story tests (may require Playwright browsers)
    cmds:
      - pnpm test:all

  coverage:
    desc: Generate unit/component test (Vitest) coverage report
    cmds:
      - pnpm coverage

  test:e2e:
    desc: Run end-to-end tests (Playwright) headlessly
    cmds:
      - pnpm test:e2e

  test:e2e:report:
    desc: Show Playwright HTML report
    cmds:
      - pnpm test:e2e:report

  test:e2e:ui:
    desc: Run end-to-end tests (Playwright) with interactive UI
    cmds:
      - pnpm test:e2e:ui

  storybook:build:
    desc: Build Storybook static site
    cmds:
      - pnpm storybook:build

  storybook:run:
    desc: Run Storybook development server
    cmds:
      - pnpm storybook:run

  codegen:
    desc: Run GraphQL code generation
    cmds:
      - pnpm codegen
