# https://taskfile.dev

version: '3.17'

dotenv:
  - .env

vars:
  DOCKER_COMPOSE: docker compose
  BACKEND_TASK: task -d backend
  FRONTEND_TASK: task -d frontend

tasks:
  docker:build:
    desc: Build services (with cache)
    cmds:
      - "{{.DOCKER_COMPOSE}} build"

  docker:build:no-cache:
    desc: Build services without cache
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache"

  docker:up:
    desc: Start services
    cmds:
      - "{{.DOCKER_COMPOSE}} up"

  docker:down:
    desc: Stop services
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  docker:down:volumes:
    desc: Stop services and remove volumes
    aliases: [docker:down:v]
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  backend:install:
    desc: Install backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} install"

  backend:migrate:
    desc: Run backend migrations
    cmds:
      - "{{.BACKEND_TASK}} migrate"

  backend:dev:
    desc: Run backend
    cmds:
      - "{{.BACKEND_TASK}} dev"

  backend:lint:fix:
    desc: Run backend lint:fix
    cmds:
      - "{{.BACKEND_TASK}} lint:fix"

  backend:format:
    desc: Run backend format
    cmds:
      - "{{.BACKEND_TASK}} format"

  backend:test:
    desc: Run backend test
    cmds:
      - "{{.BACKEND_TASK}} test"

  backend:test:cov:
    desc: Run backend test:cov
    cmds:
      - "{{.BACKEND_TASK}} test:cov"

  backend:test:cov:html:
    desc: Run backend test:cov:html
    cmds:
      - "{{.BACKEND_TASK}} test:cov:html"

  backend:typecheck:
    desc: Run backend typecheck
    cmds:
      - "{{.BACKEND_TASK}} typecheck"

  backend:create-user:
    desc: Run backend create-user
    cmds:
      - "{{.BACKEND_TASK}} create-user"

  backend:schema:export:
    desc: Export backend GraphQL schema to frontend/schema/schema.graphql
    cmds:
      - mkdir -p frontend/schema
      - "{{.BACKEND_TASK}} schema:export > frontend/schema/schema.graphql"

  frontend:install:
    desc: Install frontend dependencies
    cmds:
      - "{{.FRONTEND_TASK}} install"

  frontend:dev:
    desc: Run frontend
    cmds:
      - "{{.FRONTEND_TASK}} dev"

  frontend:lint:
    desc: Run frontend lint
    cmds:
      - "{{.FRONTEND_TASK}} lint"

  frontend:format:
    desc: Run frontend format
    cmds:
      - "{{.FRONTEND_TASK}} format"

  frontend:check:
    desc: Run frontend check
    cmds:
      - "{{.FRONTEND_TASK}} check"

  frontend:check:unsafe:
    desc: Run frontend check:unsafe
    cmds:
      - "{{.FRONTEND_TASK}} check:unsafe"

  frontend:test:run:
    desc: Run frontend test:run
    cmds:
      - "{{.FRONTEND_TASK}} test:run"

  frontend:test:ui:
    desc: Run frontend test:ui
    cmds:
      - "{{.FRONTEND_TASK}} test:ui"

  frontend:coverage:
    desc: Run frontend coverage
    cmds:
      - "{{.FRONTEND_TASK}} coverage"

  frontend:test:e2e:
    desc: Run frontend test:e2e
    cmds:
      - "{{.FRONTEND_TASK}} test:e2e"

  frontend:codegen:
    desc: Run frontend codegen
    cmds:
      - task: backend:schema:export
      - "{{.FRONTEND_TASK}} codegen"

  frontend:storybook:build:
    desc: Run frontend storybook:build
    cmds:
      - "{{.FRONTEND_TASK}} storybook:build"

  frontend:storybook:run:
    desc: Run frontend storybook:run
    cmds:
      - "{{.FRONTEND_TASK}} storybook:run"
