# https://taskfile.dev

version: '3.46'

dotenv:
  - .env

vars:
  DOCKER_COMPOSE: docker compose
  BACKEND_TASK: task -d backend
  FRONTEND_TASK: task -d frontend

tasks:
  db:pull:
    desc: Pull database image
    cmds:
      - "{{.DOCKER_COMPOSE}} pull"

  db:up:
    desc: Start database service
    cmds:
      - "{{.DOCKER_COMPOSE}} up"

  db:down:
    desc: Stop database service
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  db:down:volumes:
    desc: Stop database service and remove volumes
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  backend:install:
    desc: Install backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} install"

  backend:lock:
    desc: Upgrade backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} lock"

  backend:migrate:
    desc: Run backend migrations
    cmds:
      - "{{.BACKEND_TASK}} migrate"

  backend:migrate:make:
    desc: Generate a new migration
    cmds:
      - "{{.BACKEND_TASK}} migrate:make -- {{.CLI_ARGS}}"

  backend:dev:
    desc: Run backend
    cmds:
      - "{{.BACKEND_TASK}} dev"

  backend:lint:
    desc: Run backend lint
    cmds:
      - "{{.BACKEND_TASK}} lint"

  backend:format:
    desc: Run backend format
    cmds:
      - "{{.BACKEND_TASK}} format"

  backend:check:
    desc: Run backend check (format + lint)
    cmds:
      - "{{.BACKEND_TASK}} check"

  backend:test:
    desc: Run backend test
    cmds:
      - "{{.BACKEND_TASK}} test"

  backend:test:cov:
    desc: Run backend test:cov
    cmds:
      - "{{.BACKEND_TASK}} test:cov"

  backend:test:cov:html:
    desc: Run backend test:cov:html
    cmds:
      - "{{.BACKEND_TASK}} test:cov:html"

  backend:typecheck:
    desc: Run backend typecheck
    cmds:
      - "{{.BACKEND_TASK}} typecheck"

  backend:create-admin-user:
    desc: Create an admin user
    cmds:
      - "{{.BACKEND_TASK}} create-admin-user"

  backend:schema:export:
    desc: Export backend GraphQL schema to frontend/schema/schema.graphql
    cmds:
      - mkdir -p frontend/schema
      - "{{.BACKEND_TASK}} schema:export > frontend/schema/schema.graphql"

  frontend:install:
    desc: Install frontend dependencies
    cmds:
      - "{{.FRONTEND_TASK}} install"

  frontend:dev:
    desc: Run frontend
    cmds:
      - "{{.FRONTEND_TASK}} dev"

  frontend:lint:
    desc: Run frontend lint
    cmds:
      - "{{.FRONTEND_TASK}} lint"

  frontend:format:
    desc: Run frontend format
    cmds:
      - "{{.FRONTEND_TASK}} format"

  frontend:check:
    desc: Run frontend check (format + lint)
    cmds:
      - "{{.FRONTEND_TASK}} check"

  frontend:check:unsafe:
    desc: Run frontend check:unsafe
    cmds:
      - "{{.FRONTEND_TASK}} check:unsafe"

  frontend:check:types:
    desc: Run frontend check:types
    cmds:
      - "{{.FRONTEND_TASK}} check:types"

  frontend:validate:
    desc: Run frontend validate (check + check:types + tests)
    cmds:
      - "{{.FRONTEND_TASK}} validate"

  frontend:test:unit:
    desc: Run frontend test:unit
    cmds:
      - "{{.FRONTEND_TASK}} test:unit"

  frontend:test:unit:run:
    desc: Run frontend test:unit:run
    cmds:
      - "{{.FRONTEND_TASK}} test:unit:run"

  frontend:test:unit:ui:
    desc: Run frontend test:unit:ui
    cmds:
      - "{{.FRONTEND_TASK}} test:unit:ui"

  frontend:test:coverage:
    desc: Run frontend test:coverage
    cmds:
      - "{{.FRONTEND_TASK}} test:coverage"

  frontend:test:e2e:
    desc: Run frontend test:e2e
    cmds:
      - "{{.FRONTEND_TASK}} test:e2e"

  frontend:codegen:
    desc: Run frontend codegen
    cmds:
      - "{{.FRONTEND_TASK}} codegen"

  frontend:storybook:build:
    desc: Run frontend storybook:build
    cmds:
      - "{{.FRONTEND_TASK}} storybook:build"

  frontend:storybook:dev:
    desc: Run frontend storybook:dev
    cmds:
      - "{{.FRONTEND_TASK}} storybook:dev"
