# https://taskfile.dev

version: '3.46'

dotenv:
  - .env

vars:
  DOCKER_COMPOSE: docker compose
  BACKEND_TASK: task -d backend
  FRONTEND_TASK: task -d frontend
  IOS_TEST_DESTINATION: platform=iOS Simulator,name=iPhone 17,OS=26.2

tasks:
  infra:pull:
    desc: Pull infrastructure images
    cmds:
      - "{{.DOCKER_COMPOSE}} pull"

  db:up:
    desc: Start only database service
    cmds:
      - "{{.DOCKER_COMPOSE}} up db --wait"

  redis:up:
    desc: Start only redis service
    cmds:
      - "{{.DOCKER_COMPOSE}} up redis --wait"

  infra:up:
    desc: Start all infrastructure services (db, redis)
    cmds:
      - "{{.DOCKER_COMPOSE}} up --wait"

  db:stop:
    desc: Stop database service
    cmds:
      - "{{.DOCKER_COMPOSE}} stop db"

  redis:stop:
    desc: Stop redis service
    cmds:
      - "{{.DOCKER_COMPOSE}} stop redis"

  infra:stop:
    desc: Stop all infrastructure services
    cmds:
      - "{{.DOCKER_COMPOSE}} stop"

  infra:down:
    desc: Stop all services and remove containers
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  infra:down:volumes:
    desc: Stop all services and remove volumes
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  backend:install:
    desc: Install backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} install"

  backend:dep:add:
    desc: Add a backend dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:add -- {{.CLI_ARGS}}"

  backend:dep:add:dev:
    desc: Add a backend dev dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:add:dev -- {{.CLI_ARGS}}"

  backend:dep:remove:
    desc: Remove a backend dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:remove -- {{.CLI_ARGS}}"

  backend:dep:remove:dev:
    desc: Remove a backend dev dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:remove:dev -- {{.CLI_ARGS}}"

  backend:lock:
    desc: Upgrade backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} lock"

  backend:migrations:make:
    desc: Generate a new migration
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} migrations:make -- {{.CLI_ARGS}}"

  backend:migrations:make:empty:
    desc: Generate an empty migration
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} migrations:make:empty -- {{.CLI_ARGS}}"

  backend:migrations:migrate:
    desc: Run backend migrations
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} migrations:migrate"

  backend:migrations:revert:
    desc: Revert the latest backend migration
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} migrations:revert"

  backend:dev:
    desc: Run backend
    deps: ["infra:up"]
    cmds:
      - "{{.BACKEND_TASK}} dev"

  backend:lint:
    desc: Run backend lint
    cmds:
      - "{{.BACKEND_TASK}} lint"

  backend:format:
    desc: Run backend format
    cmds:
      - "{{.BACKEND_TASK}} format"

  backend:check:
    desc: Run backend check (format + lint)
    cmds:
      - "{{.BACKEND_TASK}} check"

  backend:typecheck:
    desc: Run backend typecheck
    cmds:
      - "{{.BACKEND_TASK}} typecheck"

  backend:audit:
    desc: Run backend dependency audit
    cmds:
      - "{{.BACKEND_TASK}} audit"

  backend:test:
    desc: Run backend test
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test -- {{.CLI_ARGS}}"

  backend:test:parallel:
    desc: Run backend tests in parallel
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test:parallel -- {{.CLI_ARGS}}"

  backend:test:cov:
    desc: Run backend test:cov
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test:cov"

  backend:test:cov:html:
    desc: Run backend test:cov:html
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test:cov:html"

  backend:create-admin-user:
    desc: Create an admin user
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} create-admin-user -- {{.CLI_ARGS}}"

  backend:schema:export:
    desc: Export backend GraphQL schema to frontend/schema/schema.graphql
    cmds:
      - mkdir -p frontend/schema
      - "{{.BACKEND_TASK}} schema:export > frontend/schema/schema.graphql"

  frontend:install:
    desc: Install frontend dependencies
    cmds:
      - "{{.FRONTEND_TASK}} install"

  frontend:dep:add:
    desc: Add a frontend dependency
    cmds:
      - "{{.FRONTEND_TASK}} dep:add -- {{.CLI_ARGS}}"

  frontend:dep:add:dev:
    desc: Add a frontend dev dependency
    cmds:
      - "{{.FRONTEND_TASK}} dep:add:dev -- {{.CLI_ARGS}}"

  frontend:dep:remove:
    desc: Remove a frontend dependency
    cmds:
      - "{{.FRONTEND_TASK}} dep:remove -- {{.CLI_ARGS}}"

  frontend:dep:remove:dev:
    desc: Remove a frontend dev dependency
    cmds:
      - "{{.FRONTEND_TASK}} dep:remove:dev -- {{.CLI_ARGS}}"

  frontend:playwright:install:
    desc: Install Playwright browser binaries for frontend tests
    cmds:
      - "{{.FRONTEND_TASK}} playwright:install"

  frontend:msw:init:
    desc: Generate frontend Mock Service Worker file
    cmds:
      - "{{.FRONTEND_TASK}} msw:init"

  frontend:dev:
    desc: Run frontend
    cmds:
      - "{{.FRONTEND_TASK}} dev"

  frontend:lint:
    desc: Run frontend lint
    cmds:
      - "{{.FRONTEND_TASK}} lint"

  frontend:format:
    desc: Run frontend format
    cmds:
      - "{{.FRONTEND_TASK}} format"

  frontend:check:
    desc: Run frontend check (format + lint)
    cmds:
      - "{{.FRONTEND_TASK}} check"

  frontend:check:unsafe:
    desc: Run frontend check:unsafe
    cmds:
      - "{{.FRONTEND_TASK}} check:unsafe"

  frontend:check:types:
    desc: Run frontend check:types
    cmds:
      - "{{.FRONTEND_TASK}} check:types"

  frontend:validate:
    desc: Run frontend validate (check + check:types + tests)
    cmds:
      - "{{.FRONTEND_TASK}} validate"

  frontend:test:unit:
    desc: Run frontend test:unit
    cmds:
      - "{{.FRONTEND_TASK}} test:unit"

  frontend:test:unit:run:
    desc: Run frontend test:unit:run
    cmds:
      - "{{.FRONTEND_TASK}} test:unit:run"

  frontend:test:unit:ui:
    desc: Run frontend test:unit:ui
    cmds:
      - "{{.FRONTEND_TASK}} test:unit:ui"

  frontend:test:coverage:
    desc: Run frontend test:coverage
    cmds:
      - "{{.FRONTEND_TASK}} test:coverage"

  frontend:test:e2e:
    desc: Run frontend test:e2e
    cmds:
      - "{{.FRONTEND_TASK}} test:e2e"

  frontend:codegen:
    desc: Run frontend codegen
    deps: ["backend:schema:export"]
    cmds:
      - "{{.FRONTEND_TASK}} codegen"

  frontend:storybook:build:
    desc: Run frontend storybook:build
    cmds:
      - "{{.FRONTEND_TASK}} storybook:build"

  frontend:storybook:dev:
    desc: Run frontend storybook:dev
    cmds:
      - "{{.FRONTEND_TASK}} storybook:dev"

  pr:create:
    desc: Create a pull request to main using /tmp/prbody.md (requires PR_TITLE; defaults branch to current)
    cmds:
      - |
        BRANCH="{{.CLI_ARGS}}"
        if [ -z "$BRANCH" ]; then
          BRANCH="$(git branch --show-current)"
        fi
        if [ -z "${PR_TITLE:-}" ]; then
          echo "Usage: PR_TITLE='<type>: <summary>' task pr:create -- <branch>" >&2
          echo "Allowed type values: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert" >&2
          exit 1
        fi
        gh pr create --base main --head "$BRANCH" --title "$PR_TITLE" --body "$(cat /tmp/prbody.md)"

  pr:edit:
    desc: Update a pull request body from /tmp/prbody.md (requires PR number)
    cmds:
      - |
        PR_NUMBER="{{.CLI_ARGS}}"
        if [ -z "$PR_NUMBER" ]; then
          echo "Usage: task pr:edit -- <pr-number>" >&2
          exit 1
        fi
        gh pr edit "$PR_NUMBER" --body "$(cat /tmp/prbody.md)"

  ios:test:
    desc: Run iOS tests
    cmds:
      - xcodebuild test -project ios/ios.xcodeproj -scheme ios -destination '{{.IOS_TEST_DESTINATION}}' -parallel-testing-enabled NO -maximum-concurrent-test-simulator-destinations 1 {{.CLI_ARGS}}

  worker:dev:
    desc: Run backend worker
    deps: ["infra:up"]
    cmds:
      - "{{.BACKEND_TASK}} worker"

  beat:dev:
    desc: Run backend beat
    deps: ["infra:up"]
    cmds:
      - "{{.BACKEND_TASK}} beat"

  flower:dev:
    desc: Run Flower monitoring
    deps: ["infra:up"]
    cmds:
      - "{{.BACKEND_TASK}} flower"
