# https://taskfile.dev

version: '3'

dotenv:
  - ../.env
  - .env

vars:
  RUFF: uv run ruff
  PYTEST: uv run pytest
  TYP: uv run ty

tasks:
  install:
    desc: Install backend dependencies
    cmds:
      - uv sync

  lock:
    desc: Upgrade backend lockfile (dependencies)
    cmds:
      - uv lock --upgrade
      - uv sync

  migrate:
    desc: Apply database migrations
    cmds:
      - uv run litestar database upgrade --no-prompt

  migrate:make:
    desc: Generate a new migration
    cmds:
      - uv run litestar database make-migrations --autogenerate -m "{{.CLI_ARGS}}"

  dev:
    desc: Run dev server
    deps: [migrate]
    cmds:
      - uv run litestar run --reload

  schema:export:
    desc: Export GraphQL schema
    cmds:
      - uv run strawberry export-schema backend.graphql.schema:schema

  lint:fix:
    desc: Run ruff to fix code linting violations
    cmds:
      - "{{.RUFF}} check --force-exclude --fix"

  format:
    desc: Run ruff to format code
    cmds:
      - "{{.RUFF}} format --force-exclude"

  typecheck:
    desc: Run ty for static type checking
    cmds:
      - "{{.TYP}} check"

  test:
    desc: Run tests without coverage
    cmds:
      - "{{.PYTEST}} --no-cov"

  test:cov:
    desc: Run tests with coverage and console report
    cmds:
      - "{{.PYTEST}}"

  test:cov:html:
    desc: Run tests with coverage and HTML report
    cmds:
      - "{{.PYTEST}} --cov-report html"

  create-admin-user:
    desc: Create an admin user
    cmds:
      - uv run python -m backend.scripts.create_admin_user
