# https://taskfile.dev

version: '3'

dotenv:
  - ../.env
  - .env

vars:
  RUFF: uv run ruff
  PYTEST: uv run pytest
  TYP: uv run ty

tasks:
  install:
    desc: Install backend dependencies
    cmds:
      - uv sync

  dep:add:
    desc: Add a backend dependency
    cmds:
      - uv add {{.CLI_ARGS}}

  dep:add:dev:
    desc: Add a backend dev dependency
    cmds:
      - uv add --dev {{.CLI_ARGS}}

  dep:remove:
    desc: Remove a backend dependency
    cmds:
      - uv remove {{.CLI_ARGS}}

  dep:remove:dev:
    desc: Remove a backend dev dependency
    cmds:
      - uv remove --dev {{.CLI_ARGS}}

  lock:
    desc: Upgrade backend lockfile (dependencies)
    cmds:
      - uv lock --upgrade
      - uv sync

  migrations:make:
    desc: Generate a new migration
    cmds:
      - uv run litestar --app backend.application:create_app database make-migrations --autogenerate -m "{{.CLI_ARGS}}"

  migrations:make:empty:
    desc: Generate an empty migration
    cmds:
      - uv run litestar --app backend.application:create_app database make-migrations --no-autogenerate -m "{{.CLI_ARGS}}"

  migrations:migrate:
    desc: Apply database migrations
    cmds:
      - uv run litestar --app backend.application:create_app database upgrade --no-prompt

  migrations:revert:
    desc: Revert the latest migration
    cmds:
      - uv run litestar --app backend.application:create_app database downgrade --no-prompt

  dev:
    desc: Run dev server
    deps: ["migrations:migrate"]
    cmds:
      - uv run litestar --app backend.application:create_app run --reload

  format:
    desc: Run ruff to format code
    cmds:
      - "{{.RUFF}} format --force-exclude"

  lint:
    desc: Run ruff to fix code linting violations
    cmds:
      - "{{.RUFF}} check --force-exclude --fix"

  check:
    desc: Run format and lint
    cmds:
      - task format
      - task lint

  typecheck:
    desc: Run ty for static type checking
    cmds:
      - "{{.TYP}} check"

  test:
    desc: Run tests without coverage
    cmds:
      - "{{.PYTEST}} --no-cov {{.CLI_ARGS}}"

  test:cov:
    desc: Run tests with coverage and console report
    cmds:
      - "{{.PYTEST}}"

  test:cov:html:
    desc: Run tests with coverage and HTML report
    cmds:
      - "{{.PYTEST}} --cov-report html"

  create-admin-user:
    desc: Create an admin user
    cmds:
      - uv run python -m backend.scripts.create_admin_user {{.CLI_ARGS}}
