# https://taskfile.dev

version: '3.46'

dotenv:
  - .env

vars:
  DOCKER_COMPOSE: docker compose
  BACKEND_TASK: task -d backend

tasks:
  infra:pull:
    desc: Pull infrastructure images
    cmds:
      - "{{.DOCKER_COMPOSE}} pull"

  db:up:
    desc: Start only database service
    cmds:
      - "{{.DOCKER_COMPOSE}} up db --wait"

  infra:up:
    desc: Start infrastructure services (db)
    cmds:
      - "{{.DOCKER_COMPOSE}} up db --wait"

  db:stop:
    desc: Stop database service
    cmds:
      - "{{.DOCKER_COMPOSE}} stop db"

  infra:stop:
    desc: Stop all infrastructure services
    cmds:
      - "{{.DOCKER_COMPOSE}} stop"

  infra:down:
    desc: Stop all services and remove containers
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  infra:down:volumes:
    desc: Stop all services and remove volumes
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  backend:install:
    desc: Install backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} install"

  backend:dep:add:
    desc: Add a backend dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:add -- {{.CLI_ARGS}}"

  backend:dep:add:dev:
    desc: Add a backend dev dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:add:dev -- {{.CLI_ARGS}}"

  backend:dep:remove:
    desc: Remove a backend dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:remove -- {{.CLI_ARGS}}"

  backend:dep:remove:dev:
    desc: Remove a backend dev dependency
    cmds:
      - "{{.BACKEND_TASK}} dep:remove:dev -- {{.CLI_ARGS}}"

  backend:lock:
    desc: Upgrade backend dependencies
    cmds:
      - "{{.BACKEND_TASK}} lock"

  backend:migrate:
    desc: Run backend migrations
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} migrate"

  backend:migrate:make:
    desc: Generate a new migration
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} migrate:make -- {{.CLI_ARGS}}"

  backend:dev:
    desc: Run backend
    deps: ["infra:up"]
    cmds:
      - "{{.BACKEND_TASK}} dev"

  backend:lint:
    desc: Run backend lint
    cmds:
      - "{{.BACKEND_TASK}} lint"

  backend:format:
    desc: Run backend format
    cmds:
      - "{{.BACKEND_TASK}} format"

  backend:check:
    desc: Run backend check (format + lint)
    cmds:
      - "{{.BACKEND_TASK}} check"

  backend:typecheck:
    desc: Run backend typecheck
    cmds:
      - "{{.BACKEND_TASK}} typecheck"

  backend:test:
    desc: Run backend test
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test -- {{.CLI_ARGS}}"

  backend:test:cov:
    desc: Run backend test:cov
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test:cov"

  backend:test:cov:html:
    desc: Run backend test:cov:html
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} test:cov:html"

  backend:create-admin-user:
    desc: Create an admin user
    deps: ["db:up"]
    cmds:
      - "{{.BACKEND_TASK}} create-admin-user -- {{.CLI_ARGS}}"

  template:prune:no-rest:
    desc: Remove REST stack while keeping GraphQL/full template
    cmds:
      - ./scripts/template-prune/apply.sh no-rest

  template:prune:no-graphql:
    desc: Remove GraphQL stack while keeping REST/full template
    cmds:
      - ./scripts/template-prune/apply.sh no-graphql

  template:prune:no-ios:
    desc: Remove iOS template
    cmds:
      - ./scripts/template-prune/apply.sh no-ios

  template:prune:rest-only:
    desc: Keep only a minimal backend REST template
    cmds:
      - ./scripts/template-prune/apply.sh rest-only

  template:prune:status:
    desc: Show template prune status and capabilities
    cmds:
      - cat .nova/template-prune-state.toml

  template:prune:validate:
    desc: Validate current repository after a prune profile
    cmds:
      - ./scripts/template-prune/validate.sh {{.CLI_ARGS}}

  pr:create:
    desc: Create a pull request to main using /tmp/prbody.md (requires PR_TITLE; defaults branch to current)
    cmds:
      - |
        BRANCH="{{.CLI_ARGS}}"
        if [ -z "$BRANCH" ]; then
          BRANCH="$(git branch --show-current)"
        fi
        if [ -z "${PR_TITLE:-}" ]; then
          echo "Usage: PR_TITLE='<type>: <summary>' task pr:create -- <branch>" >&2
          echo "Allowed type values: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert" >&2
          exit 1
        fi
        gh pr create --base main --head "$BRANCH" --title "$PR_TITLE" --body "$(cat /tmp/prbody.md)"

  pr:edit:
    desc: Update a pull request body from /tmp/prbody.md (requires PR number)
    cmds:
      - |
        PR_NUMBER="{{.CLI_ARGS}}"
        if [ -z "$PR_NUMBER" ]; then
          echo "Usage: task pr:edit -- <pr-number>" >&2
          exit 1
        fi
        gh pr edit "$PR_NUMBER" --body "$(cat /tmp/prbody.md)"
