#!/usr/bin/env bash
set -euo pipefail

# Determine script directory and root directory
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

info() { printf "\033[1;34m[info]\033[0m %s\n" "$*"; }

generate_python_env() {
  local dst="${ROOT_DIR}/.vscode/python.env"
  mkdir -p "$(dirname "$dst")"

  {
    printf "# Generated by scripts/generate_python_env.sh. Do not edit.\n"
    for src in "${ROOT_DIR}/.env" "${ROOT_DIR}/backend/.env"; do
      if [[ -f "$src" ]]; then
        sed -e 's/[[:space:]]*$//' -e '/^[[:space:]]*#/d' -e '/^[[:space:]]*$/d' "$src"
      fi
    done
  } > "$dst"

  info "Created $(realpath "$dst" 2>/dev/null || echo "$dst")"
}

generate_python_env
